version: "3"

services:
  database:
    container_name: mysql
    image: mysql/mysql-server:latest
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      # '%' means that allows to connect as root wherever.
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: admin
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    ports:
      - "3305"
    restart: always
  webapp:
    # define docker image and name
    image: y00njinuk/github-action-tutorial:latest
    container_name: github-action-tutorial
    build:
      context: . # directory path executed dockerfile
      dockerfile: dockerfile
    expose:
      - "8080"
    depends_on:
      - database